//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mxtrAutomation.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mxtrAutomation.Config.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKIAJGQPXZIOUMOBFRLA.
        /// </summary>
        internal static string GCT063_AmazoneS3AccessKey {
            get {
                return ResourceManager.GetString("GCT063_AmazoneS3AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mxtrlogobucket-test.
        /// </summary>
        internal static string GCT063_AmazoneS3BucketName {
            get {
                return ResourceManager.GetString("GCT063_AmazoneS3BucketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tN62uRfg/iJn042M0aTnWyDN5zWThdzHuSp7CNgM.
        /// </summary>
        internal static string GCT063_AmazoneS3SecretAccessKey {
            get {
                return ResourceManager.GetString("GCT063_AmazoneS3SecretAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://s3-external-1.amazonaws.com.
        /// </summary>
        internal static string GCT063_AmazoneS3ServiceURL {
            get {
                return ResourceManager.GetString("GCT063_AmazoneS3ServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ws.bullseyelocations.com/RestSearch.svc/.
        /// </summary>
        internal static string GCT063_BullseyeBaseUrl {
            get {
                return ResourceManager.GetString("GCT063_BullseyeBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GCT063_BullseyeFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("GCT063_BullseyeFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 481417419299-4kp5gue9go2048mg98fksiluijhtbmgh.apps.googleusercontent.com.
        /// </summary>
        internal static string GCT063_ClientId {
            get {
                return ResourceManager.GetString("GCT063_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZSWJVntrM8C3O3HEaUOvkIcV.
        /// </summary>
        internal static string GCT063_ClientSecret {
            get {
                return ResourceManager.GetString("GCT063_ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string GCT063_DoProcessEmail {
            get {
                return ResourceManager.GetString("GCT063_DoProcessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string GCT063_Environment {
            get {
                return ResourceManager.GetString("GCT063_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GAFiles/.
        /// </summary>
        internal static string GCT063_GAFilePath {
            get {
                return ResourceManager.GetString("GCT063_GAFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\GraycellTech\GITProjects\Mxtrautomation\Websites\mxtrAutomation.Websites.Platform\GAFiles\.
        /// </summary>
        internal static string GCT063_GAMinerFilePath {
            get {
                return ResourceManager.GetString("GCT063_GAMinerFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GCT063_GoogleAnalyticsFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("GCT063_GoogleAnalyticsFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        internal static string GCT063_Lookback {
            get {
                return ResourceManager.GetString("GCT063_Lookback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5:50,13:00,13:30.
        /// </summary>
        internal static string GCT063_MinnerRunMultipleTimes {
            get {
                return ResourceManager.GetString("GCT063_MinnerRunMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        internal static string GCT063_MinnerRunTimeZone {
            get {
                return ResourceManager.GetString("GCT063_MinnerRunTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://localhost/mxtrAutomation.
        /// </summary>
        internal static string GCT063_MongoServerSettings {
            get {
                return ResourceManager.GetString("GCT063_MongoServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.sharpspring.com/pubapi/v1/.
        /// </summary>
        internal static string GCT063_SharpspringBaseUrl {
            get {
                return ResourceManager.GetString("GCT063_SharpspringBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GCT063_SharpspringFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("GCT063_SharpspringFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKIAJGQPXZIOUMOBFRLA.
        /// </summary>
        internal static string MXTR_Staging_AmazoneS3AccessKey {
            get {
                return ResourceManager.GetString("MXTR-Staging_AmazoneS3AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mxtrlogobucket-test.
        /// </summary>
        internal static string MXTR_Staging_AmazoneS3BucketName {
            get {
                return ResourceManager.GetString("MXTR-Staging_AmazoneS3BucketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tN62uRfg/iJn042M0aTnWyDN5zWThdzHuSp7CNgM.
        /// </summary>
        internal static string MXTR_Staging_AmazoneS3SecretAccessKey {
            get {
                return ResourceManager.GetString("MXTR-Staging_AmazoneS3SecretAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://s3-external-1.amazonaws.com.
        /// </summary>
        internal static string MXTR_Staging_AmazoneS3ServiceURL {
            get {
                return ResourceManager.GetString("MXTR-Staging_AmazoneS3ServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ws.bullseyelocations.com/RestSearch.svc/.
        /// </summary>
        internal static string MXTR_Staging_BullseyeBaseUrl {
            get {
                return ResourceManager.GetString("MXTR-Staging_BullseyeBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string MXTR_Staging_BullseyeFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("MXTR-Staging_BullseyeFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 481417419299-eqqt8ffkqbadc79p9fr29loamn2t7s0m.apps.googleusercontent.com.
        /// </summary>
        internal static string MXTR_Staging_ClientId {
            get {
                return ResourceManager.GetString("MXTR-Staging_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fIyeNv8Cs7husZBz8qDLrMkH.
        /// </summary>
        internal static string MXTR_Staging_ClientSecret {
            get {
                return ResourceManager.GetString("MXTR-Staging_ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string MXTR_Staging_DoProcessEmail {
            get {
                return ResourceManager.GetString("MXTR-Staging_DoProcessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string MXTR_Staging_Environment {
            get {
                return ResourceManager.GetString("MXTR-Staging_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GAFiles/.
        /// </summary>
        internal static string MXTR_Staging_GAFilePath {
            get {
                return ResourceManager.GetString("MXTR-Staging_GAFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\GraycellTech\GITProjects\Mxtrautomation\Websites\mxtrAutomation.Websites.Platform\GAFiles\.
        /// </summary>
        internal static string MXTR_Staging_GAMinerFilePath {
            get {
                return ResourceManager.GetString("MXTR-Staging_GAMinerFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string MXTR_Staging_GoogleAnalyticsFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("MXTR-Staging_GoogleAnalyticsFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        internal static string MXTR_Staging_Lookback {
            get {
                return ResourceManager.GetString("MXTR-Staging_Lookback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00,5:00,9:00,16:00,21:00.
        /// </summary>
        internal static string MXTR_Staging_MinnerRunMultipleTimes {
            get {
                return ResourceManager.GetString("MXTR-Staging_MinnerRunMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        internal static string MXTR_Staging_MinnerRunTimeZone {
            get {
                return ResourceManager.GetString("MXTR-Staging_MinnerRunTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://localhost/mxtrAutomation.
        /// </summary>
        internal static string MXTR_Staging_MongoServerSettings {
            get {
                return ResourceManager.GetString("MXTR-Staging_MongoServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.sharpspring.com/pubapi/v1/.
        /// </summary>
        internal static string MXTR_Staging_SharpspringBaseUrl {
            get {
                return ResourceManager.GetString("MXTR-Staging_SharpspringBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string MXTR_Staging_SharpspringFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("MXTR-Staging_SharpspringFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKIAJGQPXZIOUMOBFRLA.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_AmazoneS3AccessKey {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_AmazoneS3AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mxtrlogobucket-test.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_AmazoneS3BucketName {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_AmazoneS3BucketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tN62uRfg/iJn042M0aTnWyDN5zWThdzHuSp7CNgM.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_AmazoneS3SecretAccessKey {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_AmazoneS3SecretAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://s3-external-1.amazonaws.com.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_AmazoneS3ServiceURL {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_AmazoneS3ServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ws.bullseyelocations.com/RestSearch.svc/.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_BullseyeBaseUrl {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_BullseyeBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_BullseyeFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_BullseyeFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1012139051514-u57u7dddgr27ot3s6lf6evpr88b2dt98.apps.googleusercontent.com.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_ClientId {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 917G7s4JYmInYLiyF8sWxT_g.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_ClientSecret {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_DoProcessEmail {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_DoProcessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_Environment {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GAFiles/.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_GAFilePath {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_GAFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\inetpub\wwwroot\mxtr-automation\Websites\mxtrAutomation.Websites.Platform\GAFiles\.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_GAMinerFilePath {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_GAMinerFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_GoogleAnalyticsFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_GoogleAnalyticsFirstRunBackfillMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_Lookback {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_Lookback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5:50,13:00,13:30.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_MinnerRunMultipleTimes {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_MinnerRunMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_MinnerRunTimeZone {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_MinnerRunTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://mxtr:k8KH6KjYQuRxwY8dHHsuZ3qBGSF3onJChvLQuES9@52.91.2.172/mxtrAutomation.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_MongoServerSettings {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_MongoServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.sharpspring.com/pubapi/v1/.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_SharpspringBaseUrl {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_SharpspringBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string WIN_7R1N18A6JNS_SharpspringFirstRunBackfillMonths {
            get {
                return ResourceManager.GetString("WIN-7R1N18A6JNS_SharpspringFirstRunBackfillMonths", resourceCulture);
            }
        }
    }
}
